services:
  web:
    image: nginx:alpine
    # volumes:
    #   - ../app:/usr/share/nginx/html:ro
    ports:
      - "8080:80"
    labels:
      - "dev.local=true"

  api:
    image: hashicorp/http-echo
    command: ["-listen=:3000", "-text=Hello from API"]
    ports:
      - "9090:3000"

  multi:
    image: hashicorp/http-echo
    command: ["-listen=:3000", "-text=Hello from multi-port service"]
    ports:
      - "3000:3000"
      - "8081:8080"

  ignored:
    image: redis:alpine
    labels:
      - "dev.local=false"

  custom:
    image: nginx:alpine
    ports:
      - "8082:80"
    labels:
      - "dev.local.domains=8082:myapp.custom.local;8082:myapp.alt.local"

